version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: tanstack-learn-server
    volumes:
      - server-db:/app/data
    environment:
      - DATABASE_URL=file:/app/data/local.db
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - NODE_ENV=production
    ports:
      - "${SERVER_PORT:-3000}:3000"
    restart: unless-stopped
    # Allow overriding the command to run drizzle-kit commands
    command: ${DRIZZLE_COMMAND:-sh -c "bun run dist/index.js --port ${SERVER_PORT:-3000}"}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tanstack-network

volumes:
  server-db:
    driver: local

networks:
  tanstack-network:
    driver: bridge
