services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        - DEV_DEPS=${DEV_DEPS:-false}
    container_name: tanstack-learn-server
    volumes:
      - server-db:/app/data
    environment:
      - DATABASE_URL=file:/app/data/local.db
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - NODE_ENV=production
    env_file:
      - apps/server/.env
    ports:
      - "${SERVER_PORT:-3000}:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-3000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tanstack-network

  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        - DEV_DEPS=true
    command: ["bun", "db:migrate"]
    volumes:
      - server-db:/app/data
    environment:
      - DATABASE_URL=file:/app/data/local.db
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - NODE_ENV=production
    profiles:
      - db
    networks:
      - tanstack-network

volumes:
  server-db:
    driver: local

networks:
  tanstack-network:
    driver: bridge
