services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: tanstack-learn-server
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL:-file:/app/data/production.db}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      GOOGLE_GENERATIVE_AI_API_KEY: ${GOOGLE_GENERATIVE_AI_API_KEY}
      CORS_ORIGIN: ${CORS_ORIGIN}
      PORT: 3000
      HOST_PORT: ${HOST_PORT:-3005}
      NODE_ENV: production
    volumes:
      - server_data:/app/data
    ports:
      - "${HOST_PORT:-3005}:3000"

volumes:
  server_data:
